### ISSUE TITLE
Album Image preview not working

### ISSUE THREAD

**Issue by HasanAbbadi** [pauloo27/tuner#10]
I know this feature is experimental, but it doesn't seem to work.
I installed ueberzurg and "show album set to true" and there are no errors, but it is not working 
i tried several songs but nothing shows up i even tried the songs that was in the screenshots, the same.

note : I used termite and kitty to test this.

**Comment by pauloo27** [comment]
Hello, thanks for your feedback.

I've just pushed a commit with a improvement to this feature. Can you update to the latest version in the master branch and test it?

Basically, play a song and wait around 5 seconds and try to resize your terminal. That should force the album to be displayed.

If it doesn't work, can you try to open the file `~/.cache/tuner/album` (it's a image file)? It should be the album art (or the youtube thumbnail if no albums were found).

**Comment by HasanAbbadi** [comment]
oh yeah resizing the terminal works, I'm using a window manager so i had to change different layouts until it showed, it takes time and kinda pointless but it's cool nonetheless.

**Comment by pauloo27** [comment]
Sometimes it doesn't work to me as well, but if I resize the terminal it appear.

I had the same problem with lf previews with lfimg. Unfortunately, I have no idea how to fix it.
