### ISSUE TITLE
Request Feature : Polybar module

### ISSUE THREAD

**Issue by HasanAbbadi** [pauloo27/tuner#11]
i really like this and use it daily, it would be nice to have control over it from polybar (also it would look pretty :3)
thx

**Comment by pauloo27** [comment]
You can enable MPRIS (here's how: https://github.com/Pauloo27/tuner#mpris) and then add a "mpris module" in your polybar.

I use https://github.com/Pauloo27/gotroller but any polybar mpris module should work.
