### ISSUE TITLE
Playing songs

### ISSUE THREAD

**Issue by Blind55** [pauloo27/tuner#14]
First off, really nice program! Thanks for this cool tool.
That said, the recent upgrade broke playing songs for me.

OS: ArchLinux
package: go-tuner-git (AUR)
version: r305-2126dbc (0.0.4-dev)
Symptoms:
- searching (which sometimes fails), and subsequently playing a selection 'acts' like it plays for a second, but subsequently fails
- playing a playlist seems to 'start' each song in the playlist, but subsequently just jump to the next playlist item

**Comment by pauloo27** [comment]
Hello.

It's a problem with the library Tuner uses under the hood to get the YouTube URL:

https://github.com/kkdai/youtube/issues/233

As soon as they fix the problem I will update it.

As a temporary fix you can manually build version v0.0.3 (that is working because it uses youtube-dl). 

If you want to do that, install the GoLang compiler and YouTubeDL, then clone the repo and  execute `git checkout v0.0.3` followed by `make` or `go build`.

**Comment by Blind55** [comment]
Thanks for the quick reply.

I modified the PKGBUILD to use the source

source=("${pkgname}::git+https://github.com/pauloo27/tuner#tag=v0.0.3")

and can confirm that the resulting package when installed works as expected.

**Comment by Blind55** [comment]
Looks like the issue was resolved. I am happy to recompile and test when you are ready (since youtube-dl appears to make the sound 'skippy' - maybe I need to find a cache setting...).
I assume that a fix will require pulling in the 'new' version of the go youtube library (2.7.7?)...is that the go.mod file?

**Comment by pauloo27** [comment]
> Looks like the issue was resolved. I am happy to recompile and test when you are ready (since youtube-dl appears to make the sound 'skippy' - maybe I need to find a cache setting...). I assume that a fix will require pulling in the 'new' version of the go youtube library (2.7.7?)...is that the go.mod file?

Thanks for the heads up! I upgraded to the 2.7.7 version. Works fine to me. Can you confirm?

**Comment by Blind55** [comment]
Thank you so much for your fast responses :-)
I confirm that the issue is resolved by simply re-compiling the AUR package and installing it. This issue can be closed.
