### ISSUE TITLE
Possibility of chaning the default location of playlists.

### ISSUE THREAD

**Issue by Emppu45** [pauloo27/tuner#20]
Hey!

I've been enjoying your project for a while now. It's great and works like a charm. But there is one thing that has been bothering me. 

Having playlists in .cache and lyrics in $HOME feels a bit odd. Could there be any ways of changing the default directory to something else like .config or .cache? I would highly appreciate if this was possible.  :)

**Comment by pauloo27** [comment]
Hello, thanks for the feedback.

> Having playlists in .cache and lyrics in $HOME feels a bit odd

What do you mean lyrics in $HOME? The lyrics are not stored.

The `~/.cache/tuner/data.json` is stored in the .cache since the data stored there is not supposed to be edited directly, but with commands inside tuner.

**Comment by Emppu45** [comment]
Hello!
 
 I might have mixed something with the lyrics thing. On my other system I was fetching lyrics and I thought the program was making `.lyrics` folder/file in $HOME directory. Apparently that's something else.
> The ~/.cache/tuner/data.json is stored in the .cache since the data
stored there is not supposed to be edited directly, but with commands inside tuner.
 
Ah, I see.
