### ISSUE TITLE
New issue with tuner possibly?

### ISSUE THREAD

**Issue by joel-rieke** [pauloo27/tuner#21]
I've really loved using tuner for several months now (tuner really sips on cpu but plays things very nicely), but just today, I noticed one of my songs no longer loads and plays...  I'm wondering if possibly new encodings have been introduced or something else is preventing things from playing.

I hope it is just a temporary thing...  I don't think rebooting will solve the issue.

I did notice that libmpv seems stuck on 0.32 on my system and there is a 0.35 available.  Could that be the cause?

**Comment by pauloo27** [comment]
Hello, thanks for the feedback.

I've updated some dependencies, can you try updating and testing?

**Comment by joel-rieke** [comment]
That works now.  Interesting...

**Comment by joel-rieke** [comment]
One of the things I love about tuner and why I use it almost always...  cpu utilization is only 1-2% compared to other streamers that require 15-30%.  It's still cumbersome making lists because I forget what the commands are...  If there were some way to have a very small bar with a list of shortcuts/commands for managing lists that's available even while playing something, it would be so much more usable.  But the infrastructure for tuner is super!

**Comment by pauloo27** [comment]
Sorry for the late reply.

> One of the things I love about tuner and why I use it almost always... cpu utilization is only 1-2% compared to other streamers that require 15-30%.

That's nice to hear!

 
>  If there were some way to have a very small bar with a list of shortcuts/commands for managing lists that's available even while playing something, it would be so much more usable.

I know that some of the binds are kinda bad, but you can list them by pressing "?" or even in the "save" page.

![image](https://user-images.githubusercontent.com/23013073/234055449-3a5cebb7-1526-4400-82c9-530f7cc99e42.png)

not ideal, but it's something.

![image](https://user-images.githubusercontent.com/23013073/234055488-c0faa5f3-ea48-4ed0-a69a-fa3292b6ce16.png)

**Comment by joel-rieke** [comment]
It seems like this library might be pretty cool natural integration with tuner for some of the feature(s):
https://github.com/vbauerster/mpb

Although it does look like it may somehow be getting included already or something similar to it?  :)

**Comment by pauloo27** [comment]
the progress bar code is here:
https://github.com/Pauloo27/tuner/blob/master/display/player.go#L19

(the code is kinda messy tho, sorry)

**Comment by joel-rieke** [comment]
This was fixed back in April.
