### ISSUE TITLE
Tuner not playing songs anymore

### ISSUE THREAD

**Issue by Mic2092071** [pauloo27/tuner#25]
Hello, not sure if this project is till alive but hopefully it still is, as I really like this app.

But recently tuner stopped working and can't play any songs, it tries for a few seconds and then return to the search prompt. I tried many songs and the same result happen.

Now I know it happened to me in the past and to fix it I just needed to do a full system upgrade to make sure everything is updated and it would fix it. This time I tried to reinstall it on a freshly installed and updated archlinux vm, and the same result happen. It's broken when newly installed.

Not sure if the problem is with tuner, mpv, or youtube-dl. It doesn't seems like people are having this kind of issues with youtube-dl, but maybe it's too early to say, I'm not qualified enough to know where the problem reside.

**Issue**
Songs aren't playing

**Behavior**
Songs tries to play for a few seconds, then close back to the search prompt

**Expected result**
Song would start playing

**How to replicate**
Searching and start playing any song

**Comment by pauloo27** [comment]
Hey, pushed some changes that fixed it here. Can you check please? Github closed the issue automatically when I pushed the commit, feel free to reopen if still broken for you.

**Comment by Mic2092071** [comment]
The changes are working great, amazing work, thanks!
