### ISSUE TITLE
Unable to toggle the Volume via Arrow Key Up and Down

### ISSUE THREAD

**Issue by keithkeekw** [pauloo27/tuner#5]
Try to play around with the volume but I received the message of `Cannot get MPV volume`

**Comment by pauloo27** [comment]
You probably need to copy the `/usr/share/mpv/scripts/mpris.so` to `~/.config/mpv/scripts/`

**Comment by keithkeekw** [comment]
Yeah, you are right! Now everything is working as intended. I have been testing out all the keybindings and everything works!

**Comment by keithkeekw** [comment]
Add on: Perhaps you want to put that instruction as FAQ in your README.
